server:
  port: 10112
spring:
    application:
       name: eurekaClient
eureka:
    client:
       serviceUrl:
         defaultZone: http://127.0.0.1:10111/eureka/
       healthcheck:
         enabled: false
    instance:
        lease-renewal-interval-in-seconds: 1
        lease-expiration-duration-in-seconds: 2