# spring连接数据库驱动
xhpay:
    front: db
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://10.255.57.115:3306/credit?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    #username: raccoon
    #password: gIPclG#G
    #username: niffler
    #password: Af$9RVi@
    url: jdbc:mysql://120.76.141.172:3306/credit?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Zlr@2020

# jpa自动创建不存在的数据表
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
       hibernate:
       dialect: com.ymkj.property.dialect.MyMysqlDialect
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
  jackson:
    serialization:
      indent_output: false


authservice:
  url: http://192.168.20.10:10021/
  #url: http://127.0.0.1:10113
  msgurl: /demo-gateway/src/main/resources/msg.properties
